### ISSUE TITLE
Confusing message when empty email value is submitted, should mention "email" not ": This value"

### ISSUE THREAD

**Issue by jerclarke** [mailchimp/wordpress#73]
### Describe the bug

Hi all, it's **SO GREAT** to see this plugin being actively developed again! I don't know who motivated it, but I was delighted to see there were updates for recent WP, AND fixes for long-running error log notices etc. Thanks so much! 

On to my bug: A stakeholder in our org got confused when they clicked the "subscribe" button on the outward facing form, expecting to be taken to the page, and got this error in the form:

> : This value should not be blank.

<img width="761" alt="Screenshot 2024-10-25 at 8 14 53 AM" src="https://github.com/user-attachments/assets/27cd1903-9bf9-450b-af54-ef2b1e0cf108">

They thought something was broken about the form. 

Admittedly, they clicked a submit button on a form with no data, but at the same time, I think this error message is needlessly confusing. 

If I submit with an invalid email such as `ddd`, I get the following error instead:

> Email Address: Please fill out a valid email address.

<img width="788" alt="Screenshot 2024-10-25 at 8 16 12 AM" src="https://github.com/user-attachments/assets/e4809e47-bb02-4757-ae53-aee6f5b1ca21">

To me this is MUCH clearer, and I think they would have figured it out immediately. 

So could we consider a more accurate message? Really, I'd just use the exact same message in both cases. An empty email is an invalid one, so asking them to "Please fill out a valid email address" applies in both scenarios. 

Thank you for considering this request 🙏🏻

### Steps to Reproduce

- Go to the pulic-facing form
- Click **Subscribe** without entering an email
- See an error message that could be more clear about the issue

### Environment information

Latest version of plugin

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamdharmesh** [comment]
Thanks for reporting the issue, @jerclarke. A [PR](https://github.com/mailchimp/wordpress/pull/74) has been raised to fix this issue, and it will be included in the upcoming plugin release. Thanks a lot for your contribution to improving this plugin.

**Comment by dkotter** [comment]
@jerclarke The PR looks good in my testing and I've merged that in now, but if you have some time to test and ensure it works for your situation, that would be great.

**Comment by jerclarke** [comment]
Right on! Tested the patch and the message looks nice and clear to me 🙏🏻💪🏻🎉
